title: "War Games"
description: "A blog exploring baseball stats and Python-powered sports analytics"
url: "https://silvesco94.github.io"
baseurl: "/war_games"
theme: minima

markdown: kramdown
kramdown:
  input: GFM

author:
  name: "Scott Silverstein and Ethan Arsht"

minima:
  skin: auto
  social_links: []
